version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "angularjs",
    "angular"
  ]
  environment = [
    "nodejs",
    "jest",
    "browser",
    "mocha",
    "jasmine"
  ]

[[analyzers]]
name = "swift"

[[analyzers]]
name = "php"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "1.8"
  language_version = "1.7"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "docker"